/*
 * Find the number of distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100.
 * Answer: 9183
 */

import java.math.BigInteger;
import java.util.SortedSet;
import java.util.TreeSet;

public class Problem029 {

    public void solve() {
        SortedSet<BigInteger> results = new TreeSet<>();
        BigInteger result;

        for (int a = 2; a <= 100; a++) {
            for (int b = 2, tmp = b; b <= 100; b++, tmp = b) {
                result = BigInteger.valueOf(a);
                while(tmp > 1) {
                    result = result.multiply(BigInteger.valueOf(a));
                    tmp--;
                }

                if (!results.contains(result)) {
                     results.add(result);
                }
            }
        }

        System.out.println(results.size());
    }

    public static void main(String[] args) {
        Stopwatch clock = new Stopwatch();
        clock.start();

        Problem029 p = new Problem029();
        p.solve();

        clock.stop();
    }

}
